[package]
name = "codex-acp"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "codex-acp"
path = "src/main.rs"

[lib]
name = "codex_acp"
path = "src/lib.rs"

[dependencies]
agent-client-protocol = { version = "0.4.3", features = ["unstable"] }
anyhow = "1"
async-trait = "0.1"
codex-arg0 = { git = "https://github.com/zed-industries/codex", rev = "c4120a265b9444587d6c69e170b64d2440274e10" }
codex-common = { git = "https://github.com/zed-industries/codex", rev = "c4120a265b9444587d6c69e170b64d2440274e10", features = ["cli"] }
codex-core = { git = "https://github.com/zed-industries/codex", rev = "c4120a265b9444587d6c69e170b64d2440274e10" }
codex-mcp-server = { git = "https://github.com/zed-industries/codex", rev = "c4120a265b9444587d6c69e170b64d2440274e10" }
codex-protocol = { git = "https://github.com/zed-industries/codex", rev = "c4120a265b9444587d6c69e170b64d2440274e10" }
mcp-types = { git = "https://github.com/zed-industries/codex", rev = "c4120a265b9444587d6c69e170b64d2440274e10" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "io-std", "io-util"] }
tokio-util = { version = "0.7", features = ["compat"] }
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
